name: Bug report
description: Create a report to help us improve
title: "bug: "

body:

  - type: textarea
    attributes:
      label: Describe the bug
      description: Clear and thorough explanation of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Minimum steps required to reproduce the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false