name: Feature request
description: Suggest an idea for this project
title: "feat: "

body:
        
  - type: textarea
    attributes:
      label: Describe your feature request.
      description: A clear and concise description of what the feature request is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false