name: Question
description: Ask a question
title: "question: "

body:

  - type: textarea
    attributes:
      label: Question
      description: Write your question here.
    validations:
      required: true